name: 更新 GitHub Pages

on:
  push:
    branches:
      - main
      - master
      - update-docs
    tags:
      - "v*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: 更新 GitHub Pages
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-versions: [3.8]

    steps:
      - name: 拉取代码
        uses: actions/checkout@v2

      - name: 设置 Python 环境
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: 构建文档
        run: |
          cd docs
          make html
          cd ..

      - name: 发布文档
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
